### ISSUE TITLE
support for window selection based on con_mark

### ISSUE THREAD

**Issue by dansteen** [open-dynaMIX/raiseorlaunch#7] opened 2018-01-04 15:32 UTC
Hey!

I'd love to see support for applying and recalling a window based on con_mark (https://i3wm.org/docs/userguide.html#vim_like_marks).  That would allow raiseorlaunch to be used in situations where the window title changes regularly, and the window class is not unique enough.   A common situation would be webpages in a web browser.   As a concrete example,  I can do this:
```
raiseorlaunch -e "firefox inbox.google.com" -t ".*<email>.*" -i -c firefox
```
And things work as long as I don't navigate away from google inbox (which is fine).  But if i try to do that with the aws console:
```
raiseorlaunch -e "firefox signin.aws.amazon.com" ...
```
The aws console does not provide a consistent window title, so there is no way to get the window back.

If raiseorlaunch supported con_marks we could do something like:
```
raiseorlaunch -e "firefox signin.aws.amazon.com" -m AWS
```
Then `raiseorlaunch` would mark the window on launch and we could recall the window based on the con_mark.

Thanks so much!

**Comment by open-dynaMIX** [comment] 2018-01-04 18:57
Hey!

I like the idea, however I'm afraid implementing it will be difficult. Setting a mark with `exec` is [not implemented in i3](https://github.com/i3/i3/issues/1682), so at the time we run the command, there is no reliable way to set a mark on the resulting window. When trying to do so after running the command, there are other problems, we will run into:

1. We don't know when the window is ready
2. We don't know how many windows will open from that command
3. We don't have a way to match the window

The only way I could think of right now is, that setting the mark on the window would be left to the user and raiseorlaunch would raise the window if one with the provided mark exists.

It could still be done with one command, when the argument for `-e` looks something like this:

```
"firefox --new-window ${URL}; sleep 2; i3-msg '[title=${TITLE}] mark ${MARK}'"
```

The time needed with sleep differs form usecase to usecase, so it would be a bad idea to hardcode it in raiseorlaunch.

**Comment by dansteen** [comment] 2018-01-04 20:52
https://github.com/i3/i3/issues/3109 ;-)

But aside from that,  if you are using the IPC interface to launch applications, could you not subscribe to window events (https://i3wm.org/docs/ipc.html#_window_event) and grab the next window that opens, and use the window ID?  (you could always double check to make sure the window matches the filters).

**Comment by open-dynaMIX** [comment] 2018-01-04 21:38
That would simplify things a lot :-)

Yes, the window_events also came to my mind. I will look into it a bit more as soon as I find the time.

**Comment by open-dynaMIX** [comment] 2018-01-20 16:40
This issue reminded me at -r/--scratch which has a similar problem to solve and does that with a hardcoded timeout.

The thing is, right now raiseorlaunch uses [i3-py](https://github.com/ziberna/i3-py) to communicate with i3. i3-py does not support subscribing to window events. Aside from that it's last commit is from 6 years ago. There is also [i3ipc-python](https://github.com/acrisci/i3ipc-python), which supports everything we need and seems rather active.

So the top priority at the moment is moving to i3ipc-python (#13) and fix -r/--scratch.

As soon as this is done, it will be trivial to implement the setting of marks.

However the points I mentioned above still apply, so there's a lot potential for unwanted behaviour. Specially when quickly running multiple applications.

What I definately not want is waiting for and checking events for an unlimited time (what happens if the command failed to create a window?). So there will definately be a rather short timeout when waiting for an event.

**Closed** 2018-02-08 10:19 UTC
Labels: enhancement

**Comment by open-dynaMIX** [comment] 2018-02-09 13:39
@dansteen As this is a feature I will probably not use myself, it would be nice if you could provide some feedback, if it's working as intended.
