### ISSUE TITLE
Wait for app to actually open in specific workspace

### ISSUE THREAD

**Issue by petobens** [open-dynaMIX/raiseorlaunch#16] opened 2018-08-16 23:38 UTC
Consider the following binding:
```
set $ws1 "1"
bindsym $mod+Control+l $nexec raiseorlaunch -c Slack -w $ws1
```
If I run that binding and then switch focus to a workspace other than workspace 1 then Slack (which takes some time to load) actually open on the active workspace and not the the one defined by the `-w` flag.

Can this be avoided? Thanks!

**Comment by open-dynaMIX** [comment] 2018-08-17 06:55
Hi @petobens 

Thanks for reporting this!
i3 uses listens to startup-notifications to move applications to the workspace they were opened on. Unfortunately a lot of applications have not implemented them. So the only real fix for this would be to request the developers of those applications to implement them.

Since raiseorlaunch already subscribes to window events for certain functionality, we could also use this to move the window to the right workspace. However, this solution will suffer from the same problems as described in [this issue](https://github.com/open-dynaMIX/raiseorlaunch/issues/7).

1. We don't know when the window is ready.
    There is a configurable timeout for listening to window events: `-l`/`--event-time-limit`
2. We don't know how many windows will open from that command
    We will just react on the first window that gets created. This could be not what you want in the case of applications like `gimp` that open multiple windows.

I will take a closer look into it and report back.

**Comment by petobens** [comment] 2018-08-17 14:02
Awesome. Thanks for the explanation and links.

**Comment by open-dynaMIX** [comment] 2018-08-19 19:09
A first implementation of this can be found in the develop branch. It will move all new windows created within the specified time limit. That way it will also work for applications that open multiple windows.

Thanks for bringing this up, I think that's a nice improvement :smiley:

**Comment by petobens** [comment] 2018-08-20 01:09
Awesome! Thank you so much :)

**Comment by petobens** [comment] 2018-08-26 20:02
I cannot seem to get to this to work properly (i.e it's a bit flaky)  with the following config:
```
set $mod Mod4
set $nexec exec --no-startup-id
set $ws1 "1"
set $ws2 "2"
bindsym $mod+2 workspace $ws2
bindsym $mod+Control+l $nexec raiseorlaunch -c Slack -W $ws1 -l 5
```
To reproduce this:
i) from workspace "2", run the `mod+control+l` binding
ii) raiseorlaunch will switch focus to workspace 1
iii) manually switch focus to workspace 2 with the `mod+2` binding
iv) slack finally sometimes opens in workspace 2 (and it should open in workspace 1)

I cannot seem to reproduce this consistently though. Are my settings correct? Thanks!

**Comment by open-dynaMIX** [comment] 2018-08-27 12:06
@petobens That happened to me as well, but didn't have the time to carefully investigate it yet. So far I was unable to intentionally reproduce it at all.

What you could try is increasing the timelimit. As slack is an Electron app, 5 seconds might be too optimistic :roll_eyes:
Please try setting it to something ridiculously high (like 20 or 30) just to be sure.

In the coming days, I will have the time to take a closer look.

**Comment by open-dynaMIX** [comment] 2018-08-28 07:36
For me it was just happening after a reboot, when I opened like 6 applications right after each other. Increasing the time limit fixed it for me.

You have to set `-l` to a worst-case value. This is not very elegant, but there's nothing I can do about that.

**Closed** 2018-11-07 06:58 UTC
Labels: enhancement
